export const MOCKED_PLANS = [
  {
    id: '1',
    plans: [
      {
        amount: 1138800,
        id: '110',
        interval: 'year',
        isDeprecated: false,
        name: 'BUSINESS_MAX',
      },
      {
        amount: 99900,
        id: '109',
        interval: 'month',
        isDeprecated: false,
        name: 'BUSINESS_MAX',
      },
      {
        amount: 478800,
        id: '108',
        interval: 'year',
        isDeprecated: false,
        name: 'BUSINESS_PRO',
      },
      {
        amount: 42000,
        id: '107',
        interval: 'month',
        isDeprecated: false,
        name: 'BUSINESS_PRO',
      },
      {
        amount: 250000,
        id: '106',
        interval: 'month',
        isDeprecated: false,
        name: 'ENTERPRISE_PLUS',
      },
      {
        amount: 150000,
        id: '105',
        interval: 'month',
        isDeprecated: false,
        name: 'ENTERPRISE_BASIC',
      },
      {
        amount: 0,
        id: '1',
        interval: 'month',
        isDeprecated: false,
        name: 'FREE',
      },
      {
        amount: 16000,
        id: '101',
        interval: 'month',
        isDeprecated: false,
        name: 'ESSENTIAL',
      },
      {
        amount: 42000,
        id: '102',
        interval: 'month',
        isDeprecated: false,
        name: 'PRO',
      },
      {
        amount: 0,
        id: '5',
        interval: 'month',
        isDeprecated: false,
        name: 'CUSTOM',
      },
      {
        amount: 178800,
        id: '103',
        interval: 'year',
        isDeprecated: false,
        name: 'ESSENTIAL',
      },
      {
        amount: 478800,
        id: '104',
        interval: 'year',
        isDeprecated: false,
        name: 'PRO',
      },
      {
        amount: 0,
        id: '9',
        interval: 'year',
        isDeprecated: false,
        name: 'CUSTOM',
      },
      {
        amount: 11900,
        id: '2',
        interval: 'month',
        isDeprecated: true,
        name: 'ESSENTIAL',
      },
      {
        amount: 35900,
        id: '3',
        interval: 'month',
        isDeprecated: true,
        name: 'PRO',
      },
      {
        amount: 71900,
        id: '4',
        interval: 'month',
        isDeprecated: true,
        name: 'PREMIUM',
      },
      {
        amount: 128520,
        id: '6',
        interval: 'year',
        isDeprecated: true,
        name: 'ESSENTIAL',
      },
      {
        amount: 387720,
        id: '7',
        interval: 'year',
        isDeprecated: true,
        name: 'PRO',
      },
      {
        amount: 776520,
        id: '8',
        interval: 'year',
        isDeprecated: true,
        name: 'PREMIUM',
      },
      {
        amount: 84000,
        id: '1000',
        interval: 'month',
        isDeprecated: false,
        name: 'CUSTOM_ROCKET',
      },
    ],
  },
  {
    id: '2',
    plans: [
      {
        amount: 0,
        id: '11',
        interval: 'month',
        isDeprecated: false,
        name: 'FREE',
      },
      {
        amount: 2500,
        id: '205',
        interval: 'month',
        isDeprecated: false,
        name: 'BASIC',
      },
      {
        amount: 4900,
        id: '201',
        interval: 'month',
        isDeprecated: false,
        name: 'PRO',
      },
      {
        amount: 24900,
        id: '203',
        interval: 'month',
        isDeprecated: false,
        name: 'PRO_PLUS',
      },
      {
        amount: 52900,
        id: '202',
        interval: 'year',
        isDeprecated: false,
        name: 'PRO',
      },
      {
        amount: 270000,
        id: '204',
        interval: 'year',
        isDeprecated: false,
        name: 'PRO_PLUS',
      },
      {
        amount: 5100,
        id: '13',
        interval: 'month',
        isDeprecated: true,
        name: 'PRO',
      },
      {
        amount: 54000,
        id: '16',
        interval: 'year',
        isDeprecated: true,
        name: 'PRO',
      },
      {
        amount: 24900,
        id: '210',
        interval: 'month',
        isDeprecated: false,
        name: 'MAX',
      },
      {
        amount: 270000,
        id: '211',
        interval: 'year',
        isDeprecated: false,
        name: 'MAX',
      },
    ],
  },
]

export const MOCKED_PLANS_API = {
  'query productsWithPlans': MOCKED_PLANS,
}
